/**
 * Generated by Apache Royale Compiler from org/incubatio/core/AComponent.as
 * org.incubatio.core.AComponent
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.incubatio.core.AComponent');



/**
 * @interface
 */
org.incubatio.core.AComponent = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.incubatio.core.AComponent', org.incubatio.core.AComponent);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.incubatio.core.AComponent.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'AComponent', qName: 'org.incubatio.core.AComponent', kind: 'interface' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.incubatio.core.AComponent.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {return {};},
    methods: function () {return {};}
  };
};