/**
 * Generated by Apache Royale Compiler from io/nfg/core/pathfinding/Prioritizable.as
 * io.nfg.core.pathfinding.Prioritizable
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('io.nfg.core.pathfinding.Prioritizable');

goog.require('io.nfg.core.Pos');



/**
 * @constructor
 * @extends {io.nfg.core.Pos}
 */
io.nfg.core.pathfinding.Prioritizable = function() {
  io.nfg.core.pathfinding.Prioritizable.base(this, 'constructor');
};
goog.inherits(io.nfg.core.pathfinding.Prioritizable, io.nfg.core.Pos);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('io.nfg.core.pathfinding.Prioritizable', io.nfg.core.pathfinding.Prioritizable);


/**
 * @export
 * @type {number}
 */
io.nfg.core.pathfinding.Prioritizable.prototype.priority = 0;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
io.nfg.core.pathfinding.Prioritizable.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Prioritizable', qName: 'io.nfg.core.pathfinding.Prioritizable', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
io.nfg.core.pathfinding.Prioritizable.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {
      return {
        'priority': { type: 'Number'}
      };
    },
    accessors: function () {return {};},
    methods: function () {return {};}
  };
};