/**
 * Generated by Apache Royale Compiler from io/nfg/wmg/battle/modes/Annihilation.as
 * io.nfg.wmg.battle.modes.Annihilation
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('io.nfg.wmg.battle.modes.Annihilation');

goog.require('io.nfg.wmg.battle.BattleLogic');
goog.require('io.nfg.wmg.battle.modes.AGameMode');
goog.require('io.nfg.wmg.battle.modes.IGameMode');



/**
 * @constructor
 * @extends {io.nfg.wmg.battle.modes.AGameMode}
 * @implements {io.nfg.wmg.battle.modes.IGameMode}
 * @param {Object} mode
 * @param {io.nfg.wmg.battle.BattleLogic} battle
 */
io.nfg.wmg.battle.modes.Annihilation = function(mode, battle) {
  io.nfg.wmg.battle.modes.Annihilation.base(this, 'constructor', mode, battle);
  this._pIndex = Number(mode.pIndex);
};
goog.inherits(io.nfg.wmg.battle.modes.Annihilation, io.nfg.wmg.battle.modes.AGameMode);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('io.nfg.wmg.battle.modes.Annihilation', io.nfg.wmg.battle.modes.Annihilation);


/**
 * @private
 * @type {number}
 */
io.nfg.wmg.battle.modes.Annihilation.prototype._pIndex;


/**
 * @export
 * @override
 */
io.nfg.wmg.battle.modes.Annihilation.prototype.didGameEnded = function(pIndex) {
  return this.getAlivePlayerCount() < 2;
};


/**
 * @export
 * @override
 */
io.nfg.wmg.battle.modes.Annihilation.prototype.didPlayerWin = function(pIndex) {
  return pIndex == this._pIndex && this.isEnemyAlive(pIndex) == false || pIndex != this._pIndex && this.isPlayerAlive(pIndex);
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
io.nfg.wmg.battle.modes.Annihilation.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Annihilation', qName: 'io.nfg.wmg.battle.modes.Annihilation', kind: 'class' }], interfaces: [io.nfg.wmg.battle.modes.IGameMode] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
io.nfg.wmg.battle.modes.Annihilation.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'Annihilation': { type: '', declaredBy: 'io.nfg.wmg.battle.modes.Annihilation', parameters: function () { return [  { index: 1, type: 'Object', optional: false },{ index: 2, type: 'io.nfg.wmg.battle.BattleLogic', optional: false } ]; }},
        'didGameEnded': { type: 'Boolean', declaredBy: 'io.nfg.wmg.battle.modes.Annihilation', parameters: function () { return [  { index: 1, type: 'Number', optional: false } ]; }},
        'didPlayerWin': { type: 'Boolean', declaredBy: 'io.nfg.wmg.battle.modes.Annihilation', parameters: function () { return [  { index: 1, type: 'Number', optional: false } ]; }}
      };
    }
  };
};