/**
 * Generated by Apache Royale Compiler from io/nfg/wmg/battle/modes/Assassination.as
 * io.nfg.wmg.battle.modes.Assassination
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('io.nfg.wmg.battle.modes.Assassination');

goog.require('io.nfg.wmg.battle.BattleLogic');
goog.require('io.nfg.wmg.battle.components.UnitData');
goog.require('io.nfg.wmg.battle.helpers.UnitHelper');
goog.require('io.nfg.wmg.battle.modes.AGameMode');
goog.require('org.incubatio.Entity');
goog.require('io.nfg.wmg.battle.modes.IGameMode');



/**
 * @constructor
 * @extends {io.nfg.wmg.battle.modes.AGameMode}
 * @implements {io.nfg.wmg.battle.modes.IGameMode}
 * @param {Object} mode
 * @param {io.nfg.wmg.battle.BattleLogic} battle
 */
io.nfg.wmg.battle.modes.Assassination = function(mode, battle) {
  io.nfg.wmg.battle.modes.Assassination.base(this, 'constructor', mode, battle);
  this._unit = io.nfg.wmg.battle.modes.Assassination.getUnitByName(mode.unit, this.battle.entities);
  if (!this._unit)
    throw new Error("AssassinGameModeError > unitName (" + mode.unit + ") has to be defined and to match an entity of battle !");
  if (!mode.hasOwnProperty('pIndex'))
    throw new Error("AssassinGameModeError > pindex has to be defined!");
  this._pIndex = Number(mode.pIndex);
};
goog.inherits(io.nfg.wmg.battle.modes.Assassination, io.nfg.wmg.battle.modes.AGameMode);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('io.nfg.wmg.battle.modes.Assassination', io.nfg.wmg.battle.modes.Assassination);


/**
 * @private
 * @type {io.nfg.wmg.battle.components.UnitData}
 */
io.nfg.wmg.battle.modes.Assassination.prototype._unit;


/**
 * @private
 * @type {number}
 */
io.nfg.wmg.battle.modes.Assassination.prototype._pIndex;


/**
 * @export
 * @param {string} name
 * @param {Array} entities
 * @return {io.nfg.wmg.battle.components.UnitData}
 */
io.nfg.wmg.battle.modes.Assassination.getUnitByName = function(name, entities) {
  var /** @type {number} */ i, /** @type {number} */ l = entities.length;
  for (i = 0; i < l; i++) {
    if (entities[i].getComponent(io.nfg.wmg.battle.components.UnitData).get('name') == name)
      return entities[i].getComponent(io.nfg.wmg.battle.components.UnitData);
  }
  return null;
};


/**
 * @export
 * @override
 */
io.nfg.wmg.battle.modes.Assassination.prototype.didGameEnded = function(pIndex) {
  return (io.nfg.wmg.battle.helpers.UnitHelper.getHealth(this._unit) < 1) || (!this.isPlayerAlive(pIndex) || !this.isEnemyAlive(pIndex));
};


/**
 * @export
 * @override
 */
io.nfg.wmg.battle.modes.Assassination.prototype.didPlayerWin = function(pIndex) {
  return (pIndex == this._pIndex && io.nfg.wmg.battle.helpers.UnitHelper.isDead(this._unit)) || (pIndex != this._pIndex && io.nfg.wmg.battle.helpers.UnitHelper.isAlive(this._unit));
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
io.nfg.wmg.battle.modes.Assassination.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Assassination', qName: 'io.nfg.wmg.battle.modes.Assassination', kind: 'class' }], interfaces: [io.nfg.wmg.battle.modes.IGameMode] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
io.nfg.wmg.battle.modes.Assassination.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'Assassination': { type: '', declaredBy: 'io.nfg.wmg.battle.modes.Assassination', parameters: function () { return [  { index: 1, type: 'Object', optional: false },{ index: 2, type: 'io.nfg.wmg.battle.BattleLogic', optional: false } ]; }},
        '|getUnitByName': { type: 'io.nfg.wmg.battle.components.UnitData', declaredBy: 'io.nfg.wmg.battle.modes.Assassination', parameters: function () { return [  { index: 1, type: 'String', optional: false },{ index: 2, type: 'Vector.<org.incubatio.Entity>', optional: false } ]; }},
        'didGameEnded': { type: 'Boolean', declaredBy: 'io.nfg.wmg.battle.modes.Assassination', parameters: function () { return [  { index: 1, type: 'Number', optional: false } ]; }},
        'didPlayerWin': { type: 'Boolean', declaredBy: 'io.nfg.wmg.battle.modes.Assassination', parameters: function () { return [  { index: 1, type: 'Number', optional: false } ]; }}
      };
    }
  };
};