/**
 * Generated by Apache Royale Compiler from io/nfg/wmg/battle/modes/IGameMode.as
 * io.nfg.wmg.battle.modes.IGameMode
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('io.nfg.wmg.battle.modes.IGameMode');



/**
 * @interface
 */
io.nfg.wmg.battle.modes.IGameMode = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('io.nfg.wmg.battle.modes.IGameMode', io.nfg.wmg.battle.modes.IGameMode);
/**
 * @param {number} pIndex
 * @return {boolean}
 */
io.nfg.wmg.battle.modes.IGameMode.prototype.didGameEnded = function(pIndex) {
};
/**
 * @param {number} pIndex
 * @return {boolean}
 */
io.nfg.wmg.battle.modes.IGameMode.prototype.didPlayerWin = function(pIndex) {
};
/**
 * @return {string}
 */
io.nfg.wmg.battle.modes.IGameMode.prototype.checkTrigger = function() {
};
io.nfg.wmg.battle.modes.IGameMode.prototype.start = function() {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
io.nfg.wmg.battle.modes.IGameMode.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IGameMode', qName: 'io.nfg.wmg.battle.modes.IGameMode', kind: 'interface' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
io.nfg.wmg.battle.modes.IGameMode.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {return {};},
    methods: function () {
      return {
        'didGameEnded': { type: 'Boolean', declaredBy: 'io.nfg.wmg.battle.modes.IGameMode', parameters: function () { return [  { index: 1, type: 'Number', optional: false } ]; }},
        'didPlayerWin': { type: 'Boolean', declaredBy: 'io.nfg.wmg.battle.modes.IGameMode', parameters: function () { return [  { index: 1, type: 'Number', optional: false } ]; }},
        'checkTrigger': { type: 'String', declaredBy: 'io.nfg.wmg.battle.modes.IGameMode'},
        'start': { type: 'void', declaredBy: 'io.nfg.wmg.battle.modes.IGameMode'}
      };
    }
  };
};