/**
 * Generated by Apache Royale Compiler from io/nfg/wmg/battle/modes/Peace.as
 * io.nfg.wmg.battle.modes.Peace
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('io.nfg.wmg.battle.modes.Peace');

goog.require('io.nfg.wmg.battle.BattleLogic');
goog.require('io.nfg.wmg.battle.modes.AGameMode');
goog.require('org.incubatio.Entity');
goog.require('io.nfg.wmg.battle.modes.IGameMode');



/**
 * @constructor
 * @extends {io.nfg.wmg.battle.modes.AGameMode}
 * @implements {io.nfg.wmg.battle.modes.IGameMode}
 * @param {Object} mode
 * @param {io.nfg.wmg.battle.BattleLogic} battle
 */
io.nfg.wmg.battle.modes.Peace = function(mode, battle) {
  io.nfg.wmg.battle.modes.Peace.base(this, 'constructor', mode, battle);
  if (!mode.hasOwnProperty('pIndex'))
    throw new Error("pindex has to be defined!");
  this._pIndex = Number(mode.pIndex);
};
goog.inherits(io.nfg.wmg.battle.modes.Peace, io.nfg.wmg.battle.modes.AGameMode);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('io.nfg.wmg.battle.modes.Peace', io.nfg.wmg.battle.modes.Peace);


/**
 * @private
 * @type {number}
 */
io.nfg.wmg.battle.modes.Peace.prototype._pIndex;


/**
 * @private
 * @return {boolean}
 */
io.nfg.wmg.battle.modes.Peace.prototype._hasAnyDead = function() {
  var /** @type {Array} */ goup;
  var foreachiter0_target = this.battle.deadGroups;
  for (var foreachiter0 in foreachiter0_target) 
  {
  group = foreachiter0_target[foreachiter0];
  {
    if (this.group.length > 0)
      return true;
  }}
  
  return false;
};


/**
 * @export
 * @override
 */
io.nfg.wmg.battle.modes.Peace.prototype.didGameEnded = function(pIndex) {
  return this._hasAnyDead();
};


/**
 * @export
 * @override
 */
io.nfg.wmg.battle.modes.Peace.prototype.didPlayerWin = function(pIndex) {
  return this._hasAnyDead() == false && pIndex == this._pIndex || this._hasAnyDead() && pIndex != this._pIndex;
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
io.nfg.wmg.battle.modes.Peace.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Peace', qName: 'io.nfg.wmg.battle.modes.Peace', kind: 'class' }], interfaces: [io.nfg.wmg.battle.modes.IGameMode] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
io.nfg.wmg.battle.modes.Peace.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'Peace': { type: '', declaredBy: 'io.nfg.wmg.battle.modes.Peace', parameters: function () { return [  { index: 1, type: 'Object', optional: false },{ index: 2, type: 'io.nfg.wmg.battle.BattleLogic', optional: false } ]; }},
        'didGameEnded': { type: 'Boolean', declaredBy: 'io.nfg.wmg.battle.modes.Peace', parameters: function () { return [  { index: 1, type: 'Number', optional: false } ]; }},
        'didPlayerWin': { type: 'Boolean', declaredBy: 'io.nfg.wmg.battle.modes.Peace', parameters: function () { return [  { index: 1, type: 'Number', optional: false } ]; }}
      };
    }
  };
};