/**
 * Generated by Apache Royale Compiler from io/nfg/wmg/battle/modes/StayAlive.as
 * io.nfg.wmg.battle.modes.StayAlive
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('io.nfg.wmg.battle.modes.StayAlive');

goog.require('io.nfg.wmg.battle.BattleLogic');
goog.require('io.nfg.wmg.battle.modes.AGameMode');
goog.require('io.nfg.wmg.battle.modes.IGameMode');



/**
 * @constructor
 * @extends {io.nfg.wmg.battle.modes.AGameMode}
 * @implements {io.nfg.wmg.battle.modes.IGameMode}
 * @param {Object} mode
 * @param {io.nfg.wmg.battle.BattleLogic} battle
 */
io.nfg.wmg.battle.modes.StayAlive = function(mode, battle) {
  io.nfg.wmg.battle.modes.StayAlive.base(this, 'constructor', mode, battle);
  if (!mode.hasOwnProperty('pIndex'))
    throw new Error("DefendGameModeError > pindex has to be defined!");
  this._pIndex = Number(mode.pIndex);
  this._roundLimit = Number(mode.hasOwnProperty('rounds') ? mode.rounds : 10);
};
goog.inherits(io.nfg.wmg.battle.modes.StayAlive, io.nfg.wmg.battle.modes.AGameMode);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('io.nfg.wmg.battle.modes.StayAlive', io.nfg.wmg.battle.modes.StayAlive);


/**
 * @private
 * @type {number}
 */
io.nfg.wmg.battle.modes.StayAlive.prototype._roundLimit;


/**
 * @private
 * @type {number}
 */
io.nfg.wmg.battle.modes.StayAlive.prototype._pIndex;


/**
 * @export
 * @override
 */
io.nfg.wmg.battle.modes.StayAlive.prototype.didGameEnded = function(pIndex) {
  return (!this.isPlayerAlive(pIndex) || !this.isPlayerAlive(pIndex)) || this.battle.roundNumber > this._roundLimit;
};


/**
 * @export
 * @override
 */
io.nfg.wmg.battle.modes.StayAlive.prototype.didPlayerWin = function(pIndex) {
  return (pIndex == this._pIndex && this.isPlayerAlive(pIndex)) || (pIndex != this._pIndex && this.isEnemyAlive(pIndex) == false);
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
io.nfg.wmg.battle.modes.StayAlive.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'StayAlive', qName: 'io.nfg.wmg.battle.modes.StayAlive', kind: 'class' }], interfaces: [io.nfg.wmg.battle.modes.IGameMode] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
io.nfg.wmg.battle.modes.StayAlive.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'StayAlive': { type: '', declaredBy: 'io.nfg.wmg.battle.modes.StayAlive', parameters: function () { return [  { index: 1, type: 'Object', optional: false },{ index: 2, type: 'io.nfg.wmg.battle.BattleLogic', optional: false } ]; }},
        'didGameEnded': { type: 'Boolean', declaredBy: 'io.nfg.wmg.battle.modes.StayAlive', parameters: function () { return [  { index: 1, type: 'Number', optional: false } ]; }},
        'didPlayerWin': { type: 'Boolean', declaredBy: 'io.nfg.wmg.battle.modes.StayAlive', parameters: function () { return [  { index: 1, type: 'Number', optional: false } ]; }}
      };
    }
  };
};