/**
 * Generated by Apache Royale Compiler from org/incubatio/Entity.as
 * org.incubatio.Entity
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.incubatio.Entity');

goog.require('io.nfg.wmg.battle.components.UnitData');
goog.require('org.incubatio.EventObject');
goog.require('org.apache.royale.utils.Language');



/**
 * @constructor
 * @extends {org.incubatio.EventObject}
 * @param {number} id
 */
org.incubatio.Entity = function(id) {
  org.incubatio.Entity.base(this, 'constructor');
  this.id = id;
  this._components = new Map();
};
goog.inherits(org.incubatio.Entity, org.incubatio.EventObject);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.incubatio.Entity', org.incubatio.Entity);


/**
 * @protected
 * @type {flash.utils.Dictionary}
 */
org.incubatio.Entity.prototype._components;


/**
 * @export
 * @type {number}
 */
org.incubatio.Entity.prototype.id;


/**
 * @export
 * @param {Object} component
 * @return {*}
 */
org.incubatio.Entity.prototype.addComponent = function(component) {
  var /** @type {Object} */ componentClass = org.apache.royale.utils.Language.as(component.constructor, Object, true);
  this._components.set(componentClass, component);
  return org.apache.royale.utils.Language.as(component, componentClass);
};


/**
 * @export
 * @param {Object} component
 */
org.incubatio.Entity.prototype.setComponent = function(component) {
  this.addComponent(component);
};


/**
 * Returns the component as a proper Class object. If there is no component of givent type, method returns null.
 * @export
 * @param {Object} componentClass
 * @return {*}
 */
org.incubatio.Entity.prototype.getComponent = function(componentClass) {
  return this._components.has(componentClass) ? org.apache.royale.utils.Language.as(this._components.get(componentClass), componentClass) : null;
};


/**
 * @export
 * @return {Object}
 */
org.incubatio.Entity.prototype.getComponents = function() {
  return this._components;
};


/**
 * @export
 * @return {string}
 */
org.incubatio.Entity.prototype.toString = function() {
  var /** @type {io.nfg.wmg.battle.components.UnitData} */ unitData = this.getComponent(io.nfg.wmg.battle.components.UnitData);
  return unitData && unitData.get('name') ? unitData.get('name') : '#' + this.id;
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.incubatio.Entity.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Entity', qName: 'org.incubatio.Entity', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.incubatio.Entity.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {
      return {
        'id': { type: 'Number'}
      };
    },
    accessors: function () {return {};},
    methods: function () {
      return {
        'Entity': { type: 'void', declaredBy: 'org.incubatio.Entity', parameters: function () { return [  { index: 1, type: 'Number', optional: false } ]; }},
        'addComponent': { type: '*', declaredBy: 'org.incubatio.Entity', parameters: function () { return [  { index: 1, type: 'Object', optional: false } ]; }},
        'setComponent': { type: 'void', declaredBy: 'org.incubatio.Entity', parameters: function () { return [  { index: 1, type: 'Object', optional: false } ]; }},
        'getComponent': { type: '*', declaredBy: 'org.incubatio.Entity', parameters: function () { return [  { index: 1, type: 'Class', optional: false } ]; }},
        'getComponents': { type: 'Object', declaredBy: 'org.incubatio.Entity'},
        'toString': { type: 'String', declaredBy: 'org.incubatio.Entity'}
      };
    }
  };
};
