/**
 * Generated by Apache Royale Compiler from io/nfg/wmg/battle/components/UnitData.as
 * io.nfg.wmg.battle.components.UnitData
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('io.nfg.wmg.battle.components.UnitData');
/* Royale Static Dependency List: io.nfg.wmg.models.DeckUnit,io.nfg.core.Pos*/

goog.require('io.nfg.core.Pos');
goog.require('io.nfg.core.db.AModel');
goog.require('io.nfg.wmg.models.DeckUnit');
goog.require('org.incubatio.core.AComponent');



/**
 * @constructor
 * @extends {io.nfg.core.db.AModel}
 * @implements {org.incubatio.core.AComponent}
 * @param {Object=} data
 */
io.nfg.wmg.battle.components.UnitData = function(data) {
  data = typeof data !== 'undefined' ? data : null;
  io.nfg.wmg.battle.components.UnitData.base(this, 'constructor', data, io.nfg.wmg.battle.components.UnitData.__schema, io.nfg.wmg.battle.components.UnitData.__defaults);
};
goog.inherits(io.nfg.wmg.battle.components.UnitData, io.nfg.core.db.AModel);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('io.nfg.wmg.battle.components.UnitData', io.nfg.wmg.battle.components.UnitData);


/**
 * @export
 * @const
 * @type {Array}
 */
io.nfg.wmg.battle.components.UnitData.SPECIAL_HOTKEY = ['Q', 'W', 'E', 'R'];


/**
 * @private
 * @const
 * @type {Object}
 */
io.nfg.wmg.battle.components.UnitData.__schema = {name:String, deckUnit:io.nfg.wmg.models.DeckUnit, tilePos:io.nfg.core.Pos, direction:io.nfg.core.Pos, gid:Number, pIndex:Number, hasWaited:Boolean, hasMoved:Boolean, hasFallen:Boolean, hasJumped:Boolean, passiveSkill:org.apache.royale.utils.Language.Vector, statuses:org.apache.royale.utils.Language.Vector, specialCooldowns:Object, uses:Object, specials:org.apache.royale.utils.Language.Vector, ammo:Number, riposteDoneNum:Number, unitsNumber:Number, damageTaken:Number};


/**
 * @private
 * @return {Object}
 */
io.nfg.wmg.battle.components.UnitData.__defaults = function() {
  return {ammo:0, riposteDoneNum:0, damageTaken:0, uses:{}, passiveSkill:org.apache.royale.utils.Language.Vector(), statuses:org.apache.royale.utils.Language.Vector(), specials:org.apache.royale.utils.Language.Vector(), specialCooldowns:{}};
};


/**
 * @export
 * @param {string} specialName
 * @return {string}
 */
io.nfg.wmg.battle.components.UnitData.prototype.getHotkey = function(specialName) {
  return io.nfg.wmg.battle.components.UnitData.SPECIAL_HOTKEY[this.get('specials').indexOf(specialName)];
};


/**
 * @export
 * @param {Array} specialIndexes
 * @param {Object} specialsConf
 */
io.nfg.wmg.battle.components.UnitData.prototype.reset = function(specialIndexes, specialsConf) {
  var /** @type {string} */ special;
  var /** @type {string} */ specialType;
  var /** @type {Array} */ buffList = [];
  var /** @type {number} */ i, /** @type {number} */ index;
  var /** @type {Array} */ specials = this.get('specials');
  var /** @type {Object} */ specialCooldowns = this.get('specialCooldowns');
  for (i = specialIndexes.length - 1; i > 0; i--) {
    index = Number(specialIndexes[i]);
    special = org.apache.royale.utils.Language.string(specialsConf[index]);
    specialType = special.substr(0, special.length - 1);
    if (buffList.indexOf(specialType) == -1) {
      buffList.push(specialType);
      specials.push(special);
      specialCooldowns[special] = 0;
    }
  }
};


io.nfg.wmg.battle.components.UnitData.prototype.get__deckUnit = function() {
  return this.get('deckUnit');
};


io.nfg.wmg.battle.components.UnitData.prototype.get__tilePos = function() {
  return this.get('tilePos');
};


io.nfg.wmg.battle.components.UnitData.prototype.get__type = function() {
  return this.deckUnit.get('type');
};


io.nfg.wmg.battle.components.UnitData.prototype.set__type = function(val) {
  this.deckUnit.set('type', this.type);
};


io.nfg.wmg.battle.components.UnitData.prototype.get__damageTaken = function() {
  return this.get('damageTaken');
};


io.nfg.wmg.battle.components.UnitData.prototype.set__damageTaken = function(dmg) {
  this.set('damageTaken', dmg);
};


Object.defineProperties(io.nfg.wmg.battle.components.UnitData.prototype, /** @lends {io.nfg.wmg.battle.components.UnitData.prototype} */ {
/**
  * @export
  * @type {io.nfg.wmg.models.DeckUnit} */
deckUnit: {
get: io.nfg.wmg.battle.components.UnitData.prototype.get__deckUnit},
/**
  * @export
  * @type {io.nfg.core.Pos} */
tilePos: {
get: io.nfg.wmg.battle.components.UnitData.prototype.get__tilePos},
/**
  * @export
  * @type {string} */
type: {
get: io.nfg.wmg.battle.components.UnitData.prototype.get__type,
set: io.nfg.wmg.battle.components.UnitData.prototype.set__type},
/**
  * @export
  * @type {number} */
damageTaken: {
get: io.nfg.wmg.battle.components.UnitData.prototype.get__damageTaken,
set: io.nfg.wmg.battle.components.UnitData.prototype.set__damageTaken}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
io.nfg.wmg.battle.components.UnitData.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'UnitData', qName: 'io.nfg.wmg.battle.components.UnitData', kind: 'class' }], interfaces: [org.incubatio.core.AComponent] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
io.nfg.wmg.battle.components.UnitData.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {
      return {
        'deckUnit': { type: 'io.nfg.wmg.models.DeckUnit', access: 'readonly', declaredBy: 'io.nfg.wmg.battle.components.UnitData'},
        'tilePos': { type: 'io.nfg.core.Pos', access: 'readonly', declaredBy: 'io.nfg.wmg.battle.components.UnitData'},
        'type': { type: 'String', access: 'readwrite', declaredBy: 'io.nfg.wmg.battle.components.UnitData'},
        'damageTaken': { type: 'Number', access: 'readwrite', declaredBy: 'io.nfg.wmg.battle.components.UnitData'}
      };
    },
    methods: function () {
      return {
        'UnitData': { type: '', declaredBy: 'io.nfg.wmg.battle.components.UnitData', parameters: function () { return [  { index: 1, type: 'Object', optional: true } ]; }},
        'getHotkey': { type: 'String', declaredBy: 'io.nfg.wmg.battle.components.UnitData', parameters: function () { return [  { index: 1, type: 'String', optional: false } ]; }},
        'reset': { type: 'void', declaredBy: 'io.nfg.wmg.battle.components.UnitData', parameters: function () { return [  { index: 1, type: 'Array', optional: false },{ index: 2, type: 'Object', optional: false } ]; }}
      };
    }
  };
};