/**
 * Generated by Apache Royale Compiler from io/nfg/wmg/battle/components/UnitData.as
 * io.nfg.wmg.battle.components.UnitData
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('io.nfg.wmg.battle.components.UnitData');
/* Royale Static Dependency List: io.nfg.wmg.models.DeckUnit,io.nfg.core.Pos*/

goog.require('io.nfg.core.Pos');
goog.require('io.nfg.core.db.AModel');
goog.require('io.nfg.wmg.battle.helpers.UnitHelper');
goog.require('io.nfg.wmg.models.DeckUnit');
goog.require('org.incubatio.core.AComponent');



/**
 * @constructor
 * @extends {io.nfg.core.db.AModel}
 * @implements {org.incubatio.core.AComponent}
 * @param {Object=} data
 */
io.nfg.wmg.battle.components.UnitData = function(data) {
  data = typeof data !== 'undefined' ? data : null;
  io.nfg.wmg.battle.components.UnitData.base(this, 'constructor', data, io.nfg.wmg.battle.components.UnitData.__schema, io.nfg.wmg.battle.components.UnitData.__defaults);
};
goog.inherits(io.nfg.wmg.battle.components.UnitData, io.nfg.core.db.AModel);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('io.nfg.wmg.battle.components.UnitData', io.nfg.wmg.battle.components.UnitData);


/**
 * @export
 * @const
 * @type {Array}
 */
io.nfg.wmg.battle.components.UnitData.SPECIAL_HOTKEY = ['Q', 'W', 'E', 'R'];


/**
 * @private
 * @const
 * @type {Object}
 */
io.nfg.wmg.battle.components.UnitData.__schema = {name:String, deckUnit:io.nfg.wmg.models.DeckUnit, tilePos:io.nfg.core.Pos, direction:io.nfg.core.Pos, gid:Number, pIndex:Number, hasWaited:Boolean, hasMoved:Boolean, hasFallen:Boolean, hasJumped:Boolean, passiveSkill:org.apache.royale.utils.Language.Vector, statuses:org.apache.royale.utils.Language.Vector, specialCooldowns:Object, uses:Object, ammo:Number, riposteDoneNum:Number, unitsNumber:Number, damageTaken:Number};


/**
 * @private
 * @return {Object}
 */
io.nfg.wmg.battle.components.UnitData.__defaults = function() {
  return {ammo:0, riposteDoneNum:0, damageTaken:0, uses:{}, passiveSkill:org.apache.royale.utils.Language.Vector(), statuses:org.apache.royale.utils.Language.Vector(), specialCooldowns:{}};
};


/**
 * @export
 * @param {string} specialName
 * @return {string}
 */
io.nfg.wmg.battle.components.UnitData.prototype.getHotkey = function(specialName) {
  return io.nfg.wmg.battle.components.UnitData.SPECIAL_HOTKEY[this.deckUnit.getSpecials().indexOf(this.deckUnit.allSpecials.indexOf(specialName))];
};


/**
 * @export
 * @override
 */
io.nfg.wmg.battle.components.UnitData.prototype.get = function(key) {
  if (key == 'specialCooldowns')
    this._initSpecialCooldowns();
  return io.nfg.wmg.battle.components.UnitData.superClass_.get.apply(this, [ key] );
};


/**
 * @private
 * @type {boolean}
 */
io.nfg.wmg.battle.components.UnitData.prototype._specialCooldownsInitialized;


/**
 * @export
 */
io.nfg.wmg.battle.components.UnitData.prototype._initSpecialCooldowns = function() {
  if (this._specialCooldownsInitialized == false) {
    var /** @type {Object} */ specialCooldowns = io.nfg.wmg.battle.components.UnitData.superClass_.get.apply(this, [ 'specialCooldowns'] );
    var /** @type {string} */ special;
    var foreachiter0_target = this.deckUnit.getSpecials();
    for (var foreachiter0 in foreachiter0_target) 
    {
    special = foreachiter0_target[foreachiter0];
    
      specialCooldowns[this.deckUnit.allSpecials[special]] = 0;}
    
    this._specialCooldownsInitialized = true;
  }
};


io.nfg.wmg.battle.components.UnitData.prototype.get__deckUnit = function() {
  return this.get('deckUnit');
};


io.nfg.wmg.battle.components.UnitData.prototype.get__tilePos = function() {
  return this.get('tilePos');
};


io.nfg.wmg.battle.components.UnitData.prototype.get__type = function() {
  return this.deckUnit.get('type');
};


io.nfg.wmg.battle.components.UnitData.prototype.set__type = function(val) {
  this.deckUnit.set('type', this.type);
};


io.nfg.wmg.battle.components.UnitData.prototype.get__damageTaken = function() {
  return this.get('damageTaken');
};


io.nfg.wmg.battle.components.UnitData.prototype.set__damageTaken = function(dmg) {
  this.set('damageTaken', dmg);
};


io.nfg.wmg.battle.components.UnitData.prototype.get__dim = function() {
  return io.nfg.wmg.battle.helpers.UnitHelper.getDim(this);
};


Object.defineProperties(io.nfg.wmg.battle.components.UnitData.prototype, /** @lends {io.nfg.wmg.battle.components.UnitData.prototype} */ {
/**
  * @export
  * @type {io.nfg.wmg.models.DeckUnit} */
deckUnit: {
get: io.nfg.wmg.battle.components.UnitData.prototype.get__deckUnit},
/**
  * @export
  * @type {io.nfg.core.Pos} */
tilePos: {
get: io.nfg.wmg.battle.components.UnitData.prototype.get__tilePos},
/**
  * @export
  * @type {string} */
type: {
get: io.nfg.wmg.battle.components.UnitData.prototype.get__type,
set: io.nfg.wmg.battle.components.UnitData.prototype.set__type},
/**
  * @export
  * @type {number} */
damageTaken: {
get: io.nfg.wmg.battle.components.UnitData.prototype.get__damageTaken,
set: io.nfg.wmg.battle.components.UnitData.prototype.set__damageTaken},
/**
  * @export
  * @type {number} */
dim: {
get: io.nfg.wmg.battle.components.UnitData.prototype.get__dim}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
io.nfg.wmg.battle.components.UnitData.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'UnitData', qName: 'io.nfg.wmg.battle.components.UnitData', kind: 'class' }], interfaces: [org.incubatio.core.AComponent] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
io.nfg.wmg.battle.components.UnitData.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {
      return {
        'deckUnit': { type: 'io.nfg.wmg.models.DeckUnit', access: 'readonly', declaredBy: 'io.nfg.wmg.battle.components.UnitData'},
        'tilePos': { type: 'io.nfg.core.Pos', access: 'readonly', declaredBy: 'io.nfg.wmg.battle.components.UnitData'},
        'type': { type: 'String', access: 'readwrite', declaredBy: 'io.nfg.wmg.battle.components.UnitData'},
        'damageTaken': { type: 'Number', access: 'readwrite', declaredBy: 'io.nfg.wmg.battle.components.UnitData'},
        'dim': { type: 'Number', access: 'readonly', declaredBy: 'io.nfg.wmg.battle.components.UnitData'}
      };
    },
    methods: function () {
      return {
        'UnitData': { type: '', declaredBy: 'io.nfg.wmg.battle.components.UnitData', parameters: function () { return [  { index: 1, type: 'Object', optional: true } ]; }},
        'getHotkey': { type: 'String', declaredBy: 'io.nfg.wmg.battle.components.UnitData', parameters: function () { return [  { index: 1, type: 'String', optional: false } ]; }},
        'get': { type: '*', declaredBy: 'io.nfg.wmg.battle.components.UnitData', parameters: function () { return [  { index: 1, type: '*', optional: false } ]; }},
        '_initSpecialCooldowns': { type: 'void', declaredBy: 'io.nfg.wmg.battle.components.UnitData'}
      };
    }
  };
};