/**
 * Generated by Apache Royale Compiler from io/nfg/wmg/models/Map.as
 * io.nfg.wmg.models.Map
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('io.nfg.wmg.models.Map');

goog.require('io.nfg.core.db.AModel');



/**
 * @constructor
 * @extends {io.nfg.core.db.AModel}
 * @param {Object} data
 */
io.nfg.wmg.models.Map = function(data) {
  io.nfg.wmg.models.Map.base(this, 'constructor', data, io.nfg.wmg.models.Map.__schema);
};
goog.inherits(io.nfg.wmg.models.Map, io.nfg.core.db.AModel);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('io.nfg.wmg.models.Map', io.nfg.wmg.models.Map);


/**
 * @private
 * @const
 * @type {Object}
 */
io.nfg.wmg.models.Map.__schema = {environment:String, collisions:org.apache.royale.utils.Language.Vector, seed:Number};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
io.nfg.wmg.models.Map.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Map', qName: 'io.nfg.wmg.models.Map', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
io.nfg.wmg.models.Map.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'Map': { type: '', declaredBy: 'io.nfg.wmg.models.Map', parameters: function () { return [  { index: 1, type: 'Object', optional: false } ]; }}
      };
    }
  };
};