/**
 * Generated by Apache Royale Compiler from io/nfg/wmg/models/Quest.as
 * io.nfg.wmg.models.Quest
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('io.nfg.wmg.models.Quest');

goog.require('io.nfg.core.db.AModel');



/**
 * @constructor
 * @extends {io.nfg.core.db.AModel}
 * @param {Object} data
 */
io.nfg.wmg.models.Quest = function(data) {
  io.nfg.wmg.models.Quest.base(this, 'constructor', data, io.nfg.wmg.models.Quest.io_nfg_wmg_models_Quest___schema);
};
goog.inherits(io.nfg.wmg.models.Quest, io.nfg.core.db.AModel);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('io.nfg.wmg.models.Quest', io.nfg.wmg.models.Quest);


/**
 * @private
 * @type {Object}
 */
io.nfg.wmg.models.Quest.io_nfg_wmg_models_Quest___schema = {started_at:Number, on:Boolean, prize_rng:Number, result:Boolean, missions_done:String};


/**
 * @export
 * @override
 */
io.nfg.wmg.models.Quest.prototype.set = function(key, value) {
  return io.nfg.wmg.models.Quest.superClass_.set.apply(this, [ key, value] );
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
io.nfg.wmg.models.Quest.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Quest', qName: 'io.nfg.wmg.models.Quest', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
io.nfg.wmg.models.Quest.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'Quest': { type: '', declaredBy: 'io.nfg.wmg.models.Quest', parameters: function () { return [  { index: 1, type: 'Object', optional: false } ]; }},
        'set': { type: 'io.nfg.core.db.AModel', declaredBy: 'io.nfg.wmg.models.Quest', parameters: function () { return [  { index: 1, type: '*', optional: false },{ index: 2, type: '*', optional: false } ]; }}
      };
    }
  };
};