/**
 * Generated by Apache Royale Compiler from io/nfg/wmg/models/SpecialTile.as
 * io.nfg.wmg.models.SpecialTile
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('io.nfg.wmg.models.SpecialTile');
/* Royale Static Dependency List: io.nfg.wmg.models.SpecialTile*/



/**
 * @constructor
 * @param {number} x
 * @param {number} y
 * @param {string} type
 */
io.nfg.wmg.models.SpecialTile = function(x, y, type) {
  this.x = x;
  this.y = y;
  this.type = type;
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('io.nfg.wmg.models.SpecialTile', io.nfg.wmg.models.SpecialTile);


/**
 * @export
 * @const
 * @type {string}
 */
io.nfg.wmg.models.SpecialTile.HOLE = 'H';


/**
 * @export
 * @const
 * @type {string}
 */
io.nfg.wmg.models.SpecialTile.RUN_AWAY = 'R';


/**
 * @export
 * @const
 * @type {string}
 */
io.nfg.wmg.models.SpecialTile.PORTAL = 'P';


/**
 * @export
 * @const
 * @type {Array}
 */
io.nfg.wmg.models.SpecialTile.TYPES;


/**
 * @export
 * @const
 * @type {Array}
 */
io.nfg.wmg.models.SpecialTile.FFS = [false, true, true];


/**
 * @export
 * @const
 * @type {Array}
 */
io.nfg.wmg.models.SpecialTile.FILES = ['hole', 'runaway', 'portal'];


/**
 * @export
 * @param {string} type
 * @return {string}
 */
io.nfg.wmg.models.SpecialTile.getFileFromType = function(type) {
  return io.nfg.wmg.models.SpecialTile.FILES[io.nfg.wmg.models.SpecialTile.TYPES.indexOf(type)];
};


/**
 * @export
 * @type {number}
 */
io.nfg.wmg.models.SpecialTile.prototype.x;


/**
 * @export
 * @type {number}
 */
io.nfg.wmg.models.SpecialTile.prototype.y;


/**
 * @export
 * @type {string}
 */
io.nfg.wmg.models.SpecialTile.prototype.type;


io.nfg.wmg.models.SpecialTile.prototype.get__isFF = function() {
  return io.nfg.wmg.models.SpecialTile.FFS[io.nfg.wmg.models.SpecialTile.TYPES.indexOf(this.type)];
};


Object.defineProperties(io.nfg.wmg.models.SpecialTile.prototype, /** @lends {io.nfg.wmg.models.SpecialTile.prototype} */ {
/**
  * @export
  * @type {boolean} */
isFF: {
get: io.nfg.wmg.models.SpecialTile.prototype.get__isFF}}
);

io.nfg.wmg.models.SpecialTile.TYPES = [io.nfg.wmg.models.SpecialTile.HOLE, io.nfg.wmg.models.SpecialTile.RUN_AWAY, io.nfg.wmg.models.SpecialTile.PORTAL];




/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
io.nfg.wmg.models.SpecialTile.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'SpecialTile', qName: 'io.nfg.wmg.models.SpecialTile', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
io.nfg.wmg.models.SpecialTile.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {
      return {
        'x': { type: 'Number'},
        'y': { type: 'Number'},
        'type': { type: 'String'}
      };
    },
    accessors: function () {
      return {
        'isFF': { type: 'Boolean', access: 'readonly', declaredBy: 'io.nfg.wmg.models.SpecialTile'}
      };
    },
    methods: function () {
      return {
        '|getFileFromType': { type: 'String', declaredBy: 'io.nfg.wmg.models.SpecialTile', parameters: function () { return [  { index: 1, type: 'String', optional: false } ]; }},
        'SpecialTile': { type: '', declaredBy: 'io.nfg.wmg.models.SpecialTile', parameters: function () { return [  { index: 1, type: 'Number', optional: false },{ index: 2, type: 'Number', optional: false },{ index: 3, type: 'String', optional: false } ]; }}
      };
    }
  };
};