/**
 * Generated by Apache Royale Compiler from io/nfg/core/events/NFGEvent.as
 * io.nfg.core.events.NFGEvent
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('io.nfg.core.events.NFGEvent');

goog.require('io.nfg.core.events.EventDispatcher');



/**
 * @constructor
 * @param {string} type
 * @param {boolean=} bubbles
 * @param {Object=} data
 */
io.nfg.core.events.NFGEvent = function(type, bubbles, data) {
  bubbles = typeof bubbles !== 'undefined' ? bubbles : false;
  data = typeof data !== 'undefined' ? data : null;
  this._type = type;
  this._bubbles = bubbles;
  this._data = data;
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('io.nfg.core.events.NFGEvent', io.nfg.core.events.NFGEvent);


/**
 * @private
 * @type {Array}
 */
io.nfg.core.events.NFGEvent.sEventPool = [];


/**
 * @private
 * @type {io.nfg.core.events.EventDispatcher}
 */
io.nfg.core.events.NFGEvent.prototype._target;


/**
 * @private
 * @type {io.nfg.core.events.EventDispatcher}
 */
io.nfg.core.events.NFGEvent.prototype._currentTarget;


/**
 * @private
 * @type {string}
 */
io.nfg.core.events.NFGEvent.prototype._type;


/**
 * @private
 * @type {boolean}
 */
io.nfg.core.events.NFGEvent.prototype._bubbles;


/**
 * @private
 * @type {boolean}
 */
io.nfg.core.events.NFGEvent.prototype._stopsPropagation;


/**
 * @private
 * @type {boolean}
 */
io.nfg.core.events.NFGEvent.prototype._stopsImmediatePropagation;


/**
 * @private
 * @type {Object}
 */
io.nfg.core.events.NFGEvent.prototype._data;


/**
 * @export
 */
io.nfg.core.events.NFGEvent.prototype.stopPropagation = function() {
  this._stopsPropagation = true;
};


/**
 * @export
 */
io.nfg.core.events.NFGEvent.prototype.stopImmediatePropagation = function() {
  this._stopsPropagation = this._stopsImmediatePropagation = true;
};


/**
 * @export
 * @param {io.nfg.core.events.EventDispatcher} value
 */
io.nfg.core.events.NFGEvent.prototype.setTarget = function(value) {
  this._target = value;
};


/**
 * @export
 * @param {io.nfg.core.events.EventDispatcher} value
 */
io.nfg.core.events.NFGEvent.prototype.setCurrentTarget = function(value) {
  this._currentTarget = value;
};


/**
 * @export
 * @param {Object} value
 */
io.nfg.core.events.NFGEvent.prototype.setData = function(value) {
  this._data = value;
};


/**
 * @export
 * @param {string} type
 * @param {boolean=} bubbles
 * @param {Object=} data
 * @return {io.nfg.core.events.NFGEvent}
 */
io.nfg.core.events.NFGEvent.fromPool = function(type, bubbles, data) {
  bubbles = typeof bubbles !== 'undefined' ? bubbles : false;
  data = typeof data !== 'undefined' ? data : null;
  if (io.nfg.core.events.NFGEvent.sEventPool.length)
    return io.nfg.core.events.NFGEvent.sEventPool.pop().reset(type, bubbles, data);
  else
    return new io.nfg.core.events.NFGEvent(type, bubbles, data);
};


/**
 * @export
 * @param {io.nfg.core.events.NFGEvent} event
 */
io.nfg.core.events.NFGEvent.toPool = function(event) {
  event._data = event._target = event._currentTarget = null;
  io.nfg.core.events.NFGEvent.sEventPool[io.nfg.core.events.NFGEvent.sEventPool.length] = event;
};


/**
 * @export
 * @param {string} type
 * @param {boolean=} bubbles
 * @param {Object=} data
 * @return {io.nfg.core.events.NFGEvent}
 */
io.nfg.core.events.NFGEvent.prototype.reset = function(type, bubbles, data) {
  bubbles = typeof bubbles !== 'undefined' ? bubbles : false;
  data = typeof data !== 'undefined' ? data : null;
  this._type = type;
  this._bubbles = bubbles;
  this._data = data;
  this._target = this._currentTarget = null;
  this._stopsPropagation = this._stopsImmediatePropagation = false;
  return this;
};


io.nfg.core.events.NFGEvent.prototype.get__bubbles = function() {
  return this._bubbles;
};


io.nfg.core.events.NFGEvent.prototype.get__target = function() {
  return this._target;
};


io.nfg.core.events.NFGEvent.prototype.get__currentTarget = function() {
  return this._currentTarget;
};


io.nfg.core.events.NFGEvent.prototype.get__type = function() {
  return this._type;
};


io.nfg.core.events.NFGEvent.prototype.get__data = function() {
  return this._data;
};


io.nfg.core.events.NFGEvent.prototype.get__stopsPropagation = function() {
  return this._stopsPropagation;
};


io.nfg.core.events.NFGEvent.prototype.get__stopsImmediatePropagation = function() {
  return this._stopsImmediatePropagation;
};


Object.defineProperties(io.nfg.core.events.NFGEvent.prototype, /** @lends {io.nfg.core.events.NFGEvent.prototype} */ {
/**
  * @export
  * @type {boolean} */
bubbles: {
get: io.nfg.core.events.NFGEvent.prototype.get__bubbles},
/**
  * @export
  * @type {io.nfg.core.events.EventDispatcher} */
target: {
get: io.nfg.core.events.NFGEvent.prototype.get__target},
/**
  * @export
  * @type {io.nfg.core.events.EventDispatcher} */
currentTarget: {
get: io.nfg.core.events.NFGEvent.prototype.get__currentTarget},
/**
  * @export
  * @type {string} */
type: {
get: io.nfg.core.events.NFGEvent.prototype.get__type},
/**
  * @export
  * @type {Object} */
data: {
get: io.nfg.core.events.NFGEvent.prototype.get__data},
/**
  * @export
  * @type {boolean} */
stopsPropagation: {
get: io.nfg.core.events.NFGEvent.prototype.get__stopsPropagation},
/**
  * @export
  * @type {boolean} */
stopsImmediatePropagation: {
get: io.nfg.core.events.NFGEvent.prototype.get__stopsImmediatePropagation}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
io.nfg.core.events.NFGEvent.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'NFGEvent', qName: 'io.nfg.core.events.NFGEvent', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
io.nfg.core.events.NFGEvent.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {
      return {
        'bubbles': { type: 'Boolean', access: 'readonly', declaredBy: 'io.nfg.core.events.NFGEvent'},
        'target': { type: 'io.nfg.core.events.EventDispatcher', access: 'readonly', declaredBy: 'io.nfg.core.events.NFGEvent'},
        'currentTarget': { type: 'io.nfg.core.events.EventDispatcher', access: 'readonly', declaredBy: 'io.nfg.core.events.NFGEvent'},
        'type': { type: 'String', access: 'readonly', declaredBy: 'io.nfg.core.events.NFGEvent'},
        'data': { type: 'Object', access: 'readonly', declaredBy: 'io.nfg.core.events.NFGEvent'},
        'stopsPropagation': { type: 'Boolean', access: 'readonly', declaredBy: 'io.nfg.core.events.NFGEvent'},
        'stopsImmediatePropagation': { type: 'Boolean', access: 'readonly', declaredBy: 'io.nfg.core.events.NFGEvent'}
      };
    },
    methods: function () {
      return {
        'NFGEvent': { type: '', declaredBy: 'io.nfg.core.events.NFGEvent', parameters: function () { return [  { index: 1, type: 'String', optional: false },{ index: 2, type: 'Boolean', optional: true },{ index: 3, type: 'Object', optional: true } ]; }},
        'stopPropagation': { type: 'void', declaredBy: 'io.nfg.core.events.NFGEvent'},
        'stopImmediatePropagation': { type: 'void', declaredBy: 'io.nfg.core.events.NFGEvent'},
        'setTarget': { type: 'void', declaredBy: 'io.nfg.core.events.NFGEvent', parameters: function () { return [  { index: 1, type: 'io.nfg.core.events.EventDispatcher', optional: false } ]; }},
        'setCurrentTarget': { type: 'void', declaredBy: 'io.nfg.core.events.NFGEvent', parameters: function () { return [  { index: 1, type: 'io.nfg.core.events.EventDispatcher', optional: false } ]; }},
        'setData': { type: 'void', declaredBy: 'io.nfg.core.events.NFGEvent', parameters: function () { return [  { index: 1, type: 'Object', optional: false } ]; }},
        '|fromPool': { type: 'io.nfg.core.events.NFGEvent', declaredBy: 'io.nfg.core.events.NFGEvent', parameters: function () { return [  { index: 1, type: 'String', optional: false },{ index: 2, type: 'Boolean', optional: true },{ index: 3, type: 'Object', optional: true } ]; }},
        '|toPool': { type: 'void', declaredBy: 'io.nfg.core.events.NFGEvent', parameters: function () { return [  { index: 1, type: 'io.nfg.core.events.NFGEvent', optional: false } ]; }},
        'reset': { type: 'io.nfg.core.events.NFGEvent', declaredBy: 'io.nfg.core.events.NFGEvent', parameters: function () { return [  { index: 1, type: 'String', optional: false },{ index: 2, type: 'Boolean', optional: true },{ index: 3, type: 'Object', optional: true } ]; }}
      };
    }
  };
};